### ISSUE TITLE
全体：ローディング機能を実装

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#10]
## ゴール
初回アクセス時、ローディング機能を追加

## 相談
初回に限らず、トップへ遷移する際はつけた方がいいのでしょうか？  
もしくは、一回読み込めばキャッシュ溜まるから現状の仕様のように初回ローディングで問題ないでしょか？

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
@takuan423 
>初回に限らず、トップへ遷移する際はつけた方がいいのでしょうか？
もしくは、一回読み込めばキャッシュ溜まるから現状の仕様のように初回ローディングで問題ないでしょか？
初回アクセス時のローディングだけで大丈夫って認識でＯＫですか？

**Comment by takuan423** [comment]
@ryosuke-hamamoto 
すいません、ご連絡遅くなりました。
現状は、同一セッション中は一度しか表示されないようにしています。
つまり、一度閉じたり、別タブで開く等しないと表示されないようになっています。
もし、毎回表示する方がよければすぐ対応できます！

**Comment by ryosuke-hamamoto** [comment]
@takuan423 
同一セッション中は、キャッシュ溜まってるから動画の読み込みは問題ないよーって理解でＯＫですか？？

**Comment by ryosuke-hamamoto** [comment]
クローズ
