### ISSUE TITLE
問い合わせ > 確認：数字が番号として認識されるのを調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#11]
## ゴール
スマホ時の確認画面で、郵便番号と電話番号の2つが「発信」できるようになっているので、そうならないように調整

## 調整箇所
![8_問い合わせ確認](https://user-images.githubusercontent.com/79657462/109492602-906f5880-7ace-11eb-95af-4e1f28785d5b.png)

(@k-kurihara @takuan423 )

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちらWP組み込み前の現象だと思っており、現在は現象を確認できませんでした。
まだ現象が発生するかご確認いただいてもよろしいでしょうか？

**Comment by ryosuke-hamamoto** [comment]
@k-kurihara 
ほんとですね、失礼しました！

クローズします！
