### ISSUE TITLE
入塾の流れ＆よくあるご質問：表示演出

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#12]
## ゴール
画像を1枚で表示ではなく、ブロックごとにフェード演出を入れる

## 対応箇所
![9_入塾までの流れ](https://user-images.githubusercontent.com/79657462/109493839-6a4ab800-7ad0-11eb-9322-5844059cf2f2.png)
![9-2_入塾までの流れ](https://user-images.githubusercontent.com/79657462/109493844-6ae34e80-7ad0-11eb-8394-c87e3cf2d5e1.png)

(@k-kurihara @takuan423 )

**Comment by ryosuke-hamamoto** [comment]
体験時のチェックポイントは冗長になりそうなら、ママでもいいかも。

相談したい

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応してみました。ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
PC、OKっす！

SP時で相談。
いまって一番上に要素が出たら全部が一気に表示されるけど、
講師紹介みたいに、エリアに来たら出す…とかって大変ですか？

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
「入塾の流れ」も同様にできますか？

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
OK
