### ISSUE TITLE
共通：OGとファビコンの設定

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#15]
## ゴール
OGイメージとファビコンを設置

## タスク  

1. まかおる氏デザイン  

1. はまもとチェックデザイン＆パーツ共通  

1. くりさん実装  

(@k-kurihara @takuan423 )

**Comment by ryosuke-hamamoto** [comment]
まかおるにデザイン依頼しますー。
少々お待ちを。すません

**Comment by ryosuke-hamamoto** [comment]
素材は以下に
https://drive.google.com/drive/u/1/folders/18sB4QzUxBfLmBdMkT-7JttaRfPCW0r_j

ファビコンは確定
OGは少々お待ちを。

確定後振り出します。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちらfavicon設定して、ogpも暫定で設定していますので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
OK。
クローズ
