### ISSUE TITLE
全体：「コスモNEWS」の表記ゆれ調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#16]
## ゴール
「コスモNEW」を「コスモニュース」に変更

## 変更箇所

- [ ] ヘッダー

- [ ] ニュース一覧ページのサイトタイトル

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
