### ISSUE TITLE
全体：パンくずの表記を正しいものに

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#17]
## ゴール
ページ下部にあるパンくずを、今いる階層の名前になるよう調整

## メモ
WP組み込み後に治ると思ってますが、忘れないようにissueだけ

**Comment by takuan423** [comment]
@k-kurihara 

src/html/component/_breadcrumb.pug というコンポーネントありますが、これ使ってパンくず実装してしまって大丈夫ですか？？

**Comment by ryosuke-hamamoto** [comment]
以下だけ直してください―
・コスモジュクとは
https://cosmojuku.com/about/

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応しましたのでご確認お願い致します。

http://renewal.cosmojuku.com/about/

**Comment by ryosuke-hamamoto** [comment]
クローズ
