### ISSUE TITLE
全体：ブラウザバックでのボタン表示バグ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#19]
## ゴール
スマホ時、ブラウザバックで戻ってもボタン内の文字が消えない

## 再現手順
スマホ時に「送信する」押下→ブラウザバックで前のページへ戻る→ボタンが消えている

## 閲覧環境
- iPhone8 / iOS14.4 / safari最新

## キャプチャ
![12_ブラウザバック時の問い合わせ](https://user-images.githubusercontent.com/79657462/109497508-80a74280-7ad5-11eb-80bc-63f99cc562fe.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto 
こちらは、お問い合わせページだけになりますか？それとも、他のページも一律で上記の事象になりますでしょうか？

**Comment by ryosuke-hamamoto** [comment]
対象ページのみ…と思ったら、下層ページで現象起きるみたいでしたよ

**Comment by takuan423** [comment]
@ryosuke-hamamoto
こちら多分直ったと思うので、ご確認お願い致します！
（すいません、自分の環境だと再現性がなく）

**Comment by ryosuke-hamamoto** [comment]
なおってないなぁ・・・。

問い合わせ出来上がったら、もう一度見てみます

**Comment by takuan423** [comment]
@ryosuke-hamamoto
ちなみに、たびたびお聞きしていますが、これが起きるのって「問い合わせ」だけですかね？？

**Comment by ryosuke-hamamoto** [comment]
同じあしらいのボタンをトップや下層でも使ってるけど、
なぜか問い合わせのところだけでおきます＞＜

**Comment by ryosuke-hamamoto** [comment]
やらないでいいです。
クローズ
