### ISSUE TITLE
TOP：チャットボットの表示調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#20]
## ゴール
どの端末でもチャットボットで最初の表示される要素が見切れずに表示される

## 画面キャプチャ
![13_チャットボットの見切れ](https://user-images.githubusercontent.com/79657462/109500894-32e10900-7ada-11eb-8623-6901345e0baf.png)

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto
こちら対応いたしましたので、ご確認よろしくお願いいたします。
高さの最大を端末全体の60%にしていて、iphoneSEとかでも見れていますので問題ないかと思いますが、
切れてしまっていた端末でご確認よろしくお願いいたします。

**Comment by ryosuke-hamamoto** [comment]
見切れなおってますー！！さすが！

贅沢いうと、ボタン押下後の回答出るのわかりづらいので、
押したらするするーっと回答に行くとよいのかなと思いました。
