### ISSUE TITLE
メニュー：フォントサイズと見え方の調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#25]
## ゴール
①「コスモジュクとは」「入塾までの流れ・よくあるご質問」「講師・教室紹介」のフォントサイズをすこし下げる
②デザインのように①で対応する箇所にインデントをつける

## デザインキャプチャ
![00_navigation](https://user-images.githubusercontent.com/79657462/109504090-79d0fd80-7ade-11eb-9968-f1d040e7be6c.png)
(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
