### ISSUE TITLE
TOP：コスモジュクの活動のSP時改行トリ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#26]
## ゴール
コスモジュクの
活動
↓
コスモジュクの活動
とSP時の改行をトル

## キャプチャ
![18_改行調整](https://user-images.githubusercontent.com/79657462/109504799-4b075700-7adf-11eb-8698-5ecbbfd6d72e.png)

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
iphone8 / safari 
androidone / chrome

コスモジュクの活
動

と改行されちゃってるみたいです…

![iOS の画像 (14)](https://user-images.githubusercontent.com/79657462/110263067-e83f1f80-7ff8-11eb-9ebc-1a7f7d051eb1.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
