### ISSUE TITLE
TOP：フッターのトリさんの表示演出

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#27]
## ゴール
添付画像のトリが画面左側からフェードで表示されるように

## キャプチャ
![19_トリのフェードイン](https://user-images.githubusercontent.com/79657462/109505165-a9ccd080-7adf-11eb-8ec0-a4325797bd01.png)

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応したのでご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
足跡が動いてる…のだけ気になる・・・

足跡は動かさず、トリだけ今のママっていける？

**Comment by ryosuke-hamamoto** [comment]
保留

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
クローズ
