### ISSUE TITLE
TOP：チャットボットの閉じるボタンのサイズ調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#29]
## ゴール
チャットボットの閉じるボタンのサイズを大きく

## キャプチャ
デザインに比べて小さい印象を受ける

https://user-images.githubusercontent.com/79657462/109506721-4e9bdd80-7ae1-11eb-8bfb-2ff93093b8dd.mov

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
クローズ
