### ISSUE TITLE
全体：文字回りのhover演出追加

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#3]
## ゴール
フッターの文字や、テキストボタンにhover演出を追加

## 調整内容
ヘッダーメニューと同じhover演出を追加する
![4_hover](https://user-images.githubusercontent.com/79657462/109483514-aecf5700-7ac2-11eb-965b-4b5e2d36fb4e.png)

## 変更箇所

- [ ] TOP > 記事一覧をみる

- [ ] 共通 > フッター

(@k-kurihara @takuan423 )

**Comment by ryosuke-hamamoto** [comment]
## ゴール
フッターの文字や、テキストボタンにhover演出を追加

## 調整内容
ヘッダーメニューと同じhover演出を追加する
![4_hover](https://user-images.githubusercontent.com/79657462/109483514-aecf5700-7ac2-11eb-965b-4b5e2d36fb4e.png)

## 変更箇所

- [ ] TOP > 記事一覧をみる

- [ ] 共通 > フッター

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら意図しているものは、ホバー時に矢印が動く、というものであっていますか？？

**Comment by ryosuke-hamamoto** [comment]
テレカン時にも伝えましたが。
認識合ってます！

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします。

**Comment by ryosuke-hamamoto** [comment]
クローズ
