### ISSUE TITLE
入塾の流れ＆よくあるご質問：文字の段落ち調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#30]
## ゴール
添付の赤枠部分の文字がきれいに上の段に収まる
or
違和感のない見え方になる

## キャプチャ
![21_文字調整](https://user-images.githubusercontent.com/79657462/109507735-61fb7880-7ae2-11eb-852d-951610c19a7b.png)

## 相談
収まらないから改行位置をユニークでつけた方がいいよーって話＋こっちでPC/SPの改行位置を指定した方が良ければ言ってください！

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら、文字の級数を上げるor下げる、もしくは幅を広げることで解決できるのかなと思いますが、いかがでしょう。
改行位置を変えるというのも手ですが、文章見た時に、文章として適切に改行できるものばかりでもなさそうな気がしており。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

別issueでもご連絡していますが、対応していますのでご確認お願いします。

**Comment by ryosuke-hamamoto** [comment]
issue被りすません。
#38 クローズしました。


以下対応お願いします。

体験時のチェックポイント
も同じ対応お願いします。

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら級数あげて対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
最後に余力合ったら微調整しよう。

クローズ
