### ISSUE TITLE
コスモジュクとは：安心ポイントのLINEエリアの見え方

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#31]
## ゴール
添付のような見た目にする

## キャプチャ
![22_安心ポイントLINE](https://user-images.githubusercontent.com/79657462/109510333-35952b80-7ae5-11eb-8c15-ed35e5898c4c.png)

## 相談
いざ上がってきたら、めちゃ違和感を感じました。。。
可能かどうか相談させてください。

**Comment by ryosuke-hamamoto** [comment]
見た目完璧！！ 

タイトルをテキストを
`LINEの積極活用。学習塾がより身近な存在に`
↓
`LINEの積極活用。`
に変更

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応しましたので、ご確認お願いしますmm

**Comment by ryosuke-hamamoto** [comment]
クローズ
