### ISSUE TITLE
コスモジュクとは：学びの特徴の動画バグ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#32]
issue分けた方が良ければ言ってください

## ゴール
SP時にサムネが表示され、動画がサムネ内で再生されるようになる
PC時に再生ボタン押下後、動画が固まらずスムーズに再生されるようになる

## 発生するバグ

- [pc]：再生マーク押下後、1秒ほどは動画が流れるがその後固まる

- [sp]：動画のサムネが表示されない

- [sp]：動画が1回clickしただけじゃ再生されない（反応が悪い？って感じなのかな？）

-[sp]：PC時と違ってモーダルが立ち上がっての再生となる（PCと同じくサムネ内に流れる仕様がいい）

## 閲覧環境
iPhone8 / iOS14 / safari最新
win10 / chrome最新

キャプチャ
![iOS の画像 (9)](https://user-images.githubusercontent.com/79657462/109510703-adfbec80-7ae5-11eb-82e7-bbd55a067af9.png)

## 相談
「再生」・「ストップ」・「もう一度再生」の3つが必要だと思ったんだけど、デザイン必要？
もしくはなくても大丈夫なような見せ方ってありますかね？

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応してみました。直っているか確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
２～３sほど固まるのは、動画の重さ？軽量化がまだだからかな？

一回タブ閉じて、再度開くと止まっちゃうから
再生マークつけるor再生できるようにしないと解決しないかも

**Comment by takuan423** [comment]
停止したら再生ボタンを出す

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
別の画面から戻ってくると、やっぱり再生マーク表示されない・・・。。

**Comment by takuan423** [comment]
@ryosuke-hamamoto

もう少し調整してみました。再生マークはこれで出るはず。。
ただ、動画再生状態でページ遷移→ブラウザバック でもどる、のときに
動画を停止＆初期状態にする、がどうしても実現が難しい模様です。
動画停止状態でページ遷移→ブラウザバック でもどる、のときには期待通りの挙動になっているかと思います。

**Comment by ryosuke-hamamoto** [comment]
クローズ
