### ISSUE TITLE
全体：フォント調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#34]
## ゴール
以下の対応が完了する

## まかおるFB
①SPだとウェブフォントが効いていない。
②見出し周りのウエイトを「bold700」に設定（PC/SPともに）
（PSDで「Black」と指定しているところです。普通のbold指定だと少し細くなってしまうので）
https://fonts.google.com/specimen/Noto+Sans+JP?preview.text_type=custom&query=noto

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

フォント、webフォント読み込んでboldの指定調整しました。ご確認お願いします。

**Comment by ryosuke-hamamoto** [comment]
クローズ
