### ISSUE TITLE
TOP：コース紹介エリアのデザイン調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#35]
## ゴール
要相談

## 対応内容（希望）
スマホ時、コース紹介エリアで下部の一覧ページに到達するまでが長い
そのため各コースにアンカーリンクつけたい。（各コースに矢印など付けて）
上記に加えて、「オリジナルコース」「オンラインコース」などの見出しは
フォントサイズを2pxくらい小さくする。

## 対応箇所
![image](https://user-images.githubusercontent.com/79657462/109580895-ba606380-7b3e-11eb-8b4f-e0f7e2b2ee78.png)

#### 相談
SP時横書きにするっていう選択肢あったりしますかね？？
以下みたいな感じ
![SP時のコース紹介](https://user-images.githubusercontent.com/79657462/109581393-93566180-7b3f-11eb-9447-8abe2848cbf2.png)

**Comment by ryosuke-hamamoto** [comment]
@k-kurihara @takuan423 
PSDアップしました。
https://drive.google.com/drive/u/1/folders/1QjmJWTYtffsx8LY0C7yt9gC3NAyrhi63  
```
【トップページ変更箇所】
①見出し：SPのみ、横書き＆フォントサイズ下げ＆センタリング
②イラスト：サイズを一回り小さく（PCはオリジナルコース、チュートリアルコースのみ、SPは全コース）
③各コースにリンク追加＆それに伴い、
元々あったボタンのラベリングを変更(↓)
「コースの詳細を見る」→「コースの一覧を見る」
```

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
