### ISSUE TITLE
入塾の流れ＆よくあるご質問：テキスト変更

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#38]
## ゴール
入塾までの流れ、体験時のチェックポイントの打ち文字を差し替え

## 対応箇所のテキスト 
https://docs.google.com/spreadsheets/d/1tgs3_grmcgztODBs_RSA6qlgXq-kbuXe/edit#gid=1556545092&range=B4:M10

![txt修正](https://user-images.githubusercontent.com/79657462/109897468-16112500-7cd6-11eb-9549-84b9e638d73f.png)

**Comment by ryosuke-hamamoto** [comment]
PCの時、段落ちしてるテキストが気持ちわるい
文字のサイズを小さくor左右の幅を広げる…でどうにかならないものだろうか…？
「入塾」が少し長いから難しい・・・？
![aaaa](https://user-images.githubusercontent.com/79657462/110202340-3a722a80-7eab-11eb-90c0-118e9b7e1d3d.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

級数をわずかに上げて対応していますので、ご確認お願いしますmm

**Comment by ryosuke-hamamoto** [comment]
体験時のチェックポイント
も同じ対応お願いします。

**Comment by ryosuke-hamamoto** [comment]
#30 で続けます―。

こっちはテキスト確認できたんでクローズ
