### ISSUE TITLE
講師＆教室紹介：店舗追加

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#39]
## ゴール
日限丸山台スクールの下に、同じフォーマットで別所スクールを追加

##  対応箇所
営業時間は同じで大丈夫です。
https://docs.google.com/spreadsheets/d/1QMITWBBeNT4XOWWrz_uR0sszLXp3WmN7diA2JDC41VM/edit#gid=1556545092&range=B15:J17

![店舗追加](https://user-images.githubusercontent.com/79657462/109896055-a306af00-7cd3-11eb-8d76-0541def11f8d.png)

**Comment by ryosuke-hamamoto** [comment]
かんぺき！！！

添付のように番号を入れることは可能でしょか？
![aaaa](https://user-images.githubusercontent.com/79657462/110202413-b9676300-7eab-11eb-8e9f-6f0cdfeec12a.png)

別issueの必要あれば言ってください。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

電話番号追加しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
完璧！
クローズ
