### ISSUE TITLE
TOP：MV動画のバグ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#4]
## ゴール
どのような状況でも動画が再生される

## 発生するバグ
- キービジュアルのMV動画エリアにずっといると、動画が止まって動かない
- 他のタブやページから戻ってくると動画が表示されず、真っ白の背景になる

## 閲覧環境
- Win10 / Chrome最新 

## 動画キャプチャ
https://user-images.githubusercontent.com/79657462/109478669-e0452400-7abc-11eb-95a7-ff64a2c75d60.mp4

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
KVの動画、動かずに止まってるっすね…

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

おや、、、？
動画が止まる端末、ブラウザ、条件を教えていただきたいです！

**Comment by ryosuke-hamamoto** [comment]
iPhone8 iOS最新 saafri
です！
（シークレットブラウザで見てます。低電力モードではありません！）

**Comment by ryosuke-hamamoto** [comment]
条件は、
別のタブやアプリを開いて（一度ページから離脱）戻ること

**Comment by takuan423** [comment]
@ryosuke-hamamoto  
ありがとうございます。なるほど、、。
ちなみに、このサイトでも同じ状態になりますかね？
(topの背景がvideoタグ動画のループ)

https://recruit.livesense.co.jp

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちらレスがないので、、
ちょっと自分の方で考えて実装してみました。

おそらく、下記のサイトでも、別のタブやアプリを開いてページに戻ると背景動画が止まるんじゃないかと思います。
なので、下記のサイト同様で、

- 動画がページビュー外になったら動画を止める
- 動画がページビュー内に入ったら動画を再生する

という仕様にしました。
これは上記の「別のタブやアプリを開いてページに戻ると背景動画が止まる」という問題を解決できていませんが、
一度動画が止まってしまったユーザーが永遠に動画の再度の再生機会を失うという事象は回避できるかと思います。

パフォーマンスの面でも、ページビュー外の動画が延々と無限ループしているのは芳しくないと思うので、
この仕様と取り入れましたがいかがでしょうか。

https://recruit.livesense.co.jp

**Comment by ryosuke-hamamoto** [comment]
返事できておらず、、失礼しました！！

突っ込まれたらまた相談させてください。

一旦ペンディング

**Comment by ryosuke-hamamoto** [comment]
クローズ
