### ISSUE TITLE
コース＆料金：金額を税込表記に変更

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#40]
## ゴール
料金表の金額を税込表示に変更し、料金表の下に「※税込表記」のテキストを追加

## 経緯
2021年4月からの法改正により、対応がマスト・・・・・・・

## 対応箇所
![税込表記](https://user-images.githubusercontent.com/79657462/110147476-0e10cc80-7e1f-11eb-8f1e-bbe4ed408ebc.png)

## 料金表
https://docs.google.com/spreadsheets/d/1tgs3_grmcgztODBs_RSA6qlgXq-kbuXe/edit#gid=760681814

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
クローズ
