### ISSUE TITLE
コース紹介：横スクロールが発生

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#41]
## ゴール
横スクロールがなくなる

## 現象
1170pxあたりから横スクロールが発生する

![yoko](https://user-images.githubusercontent.com/79657462/110234108-1591bc00-7f6c-11eb-9a6f-93b3843c0613.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
