### ISSUE TITLE
コース紹介：時間割の要素が隠れる

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#42]
## ゴール
時間割の要素がすべて表示されること

## 現象
時間割の要素が見切れている

![yoko](https://user-images.githubusercontent.com/79657462/110234159-470a8780-7f6c-11eb-8bdb-257172c6c95c.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
