### ISSUE TITLE
コース紹介：テーブルの高さ調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#43]
## ゴール
テーブルの高さを調整

## 対応
SPのみ
.p-course__menu__pricelist td
のサイズを変更
4.392386530014641vw
↓
3.3vw

↑に直してくれっていうよりも、高さを削りたいって話です。

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
