### ISSUE TITLE
講師&教室紹介：見たい場所をタップ！の表示崩れ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#44]
## ゴール
見たい場所をタップ！の表示崩れがなおる
![image](https://user-images.githubusercontent.com/79657462/110234406-a5843580-7f6d-11eb-99ca-a348e7648094.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto 対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
