### ISSUE TITLE
コース紹介：PC時の横スクロールバー

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#45]
## ゴール
PC時、横スクロールバーが表示されない

## 相談
PC時はスクロールバーのエリア（写真の部分）を出さないようにできますか？

![yoko](https://user-images.githubusercontent.com/79657462/110234544-61456500-7f6e-11eb-84a7-de9585bce0b6.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
