### ISSUE TITLE
コース紹介：SP時の料金表の見え方

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#46]
## ゴール
横スクロールできることがわかる

## 対応
横スクロールできるってのがわかりづらいから
https://appleple.github.io/scroll-hint/ 
みたいなの入れることはできますか？

![iOS の画像 (11)](https://user-images.githubusercontent.com/79657462/110234667-11b36900-7f6f-11eb-90d3-1d5ada3855f6.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応してみました。ご確認お願いいたします。

**Comment by ryosuke-hamamoto** [comment]
大変よき！
クローズ
