### ISSUE TITLE
コース料金：「取り扱い」のフォントサイズ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#47]
## ゴール
祝日の取り扱い、欠席時の取り扱いのフォントサイズが適正な大きさになる

![iOS の画像 (12)](https://user-images.githubusercontent.com/79657462/110234674-1ed05800-7f6f-11eb-82a9-31861deffa6b.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
