### ISSUE TITLE
コース料金：料金表の修正

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#48]
## ゴール
南中コースの備考の金額を修正

## 対応箇所
模試代金：5,500
教材代4,5年：2,200
教材代6年：19,800
成果報酬：1,210

![1](https://user-images.githubusercontent.com/79657462/110234932-791de880-7f70-11eb-890c-504d1484a5ed.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
