### ISSUE TITLE
コース料金：時間割の文字ずれ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#49]
## ゴール
時間割の時間をデザインのように左詰めにする

![iOS の画像 (13)](https://user-images.githubusercontent.com/79657462/110235529-d7989600-7f73-11eb-9130-bcbe707e0f9c.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
