### ISSUE TITLE
TOP：足跡演出

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#5]
## ゴール
足跡を以下のように調整する

## 調整内容
- [ ] コスモニュース上の足跡
「コース詳細をみる」ボタンの表示と一緒のタイミングで足跡も表示
![1_足跡演出](https://user-images.githubusercontent.com/79657462/109481879-abd36700-7ac0-11eb-87ca-0058d051f094.png)

- [ ] コスモニュース下の足跡
「記事一覧をみる」の表示と一緒のタイミングで足跡も表示
![1-2_足跡演出](https://user-images.githubusercontent.com/79657462/109481885-ad9d2a80-7ac0-11eb-959d-ac143b685ff7.png)

## 調整理由
下のコンテンツに続く意味での足跡なので、その上のコンテンツが表示されたタイミングで足跡を出したいため
（伝わる…？） 

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
速攻直すぞ

**Comment by takuan423** [comment]
@ryosuke-hamamoto
この足跡の箇所の実装方法変えました。
ので、タイミング・スピードある程度自由に調整できます。
一応暫定でもう少しコンテンツの変わり目で出るように調整していますので、ご確認お願いします。

**Comment by ryosuke-hamamoto** [comment]
このままでいいと思う！
クローズ
