### ISSUE TITLE
コース料金：学年トリ対応

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#50]
## ゴール
小学5年、小学6年、中学1年…などの「学年」をトリ
小5、小6…など取った状態に統一

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
オリジナルコースの時間割も同じ対応おねがいします！

中学1年 英語 → 中1 英語
中学1,2年 CCC → 中1,2 CCC
のようにできるとよいです。

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応したのでご確認お願いします！

**Comment by ryosuke-hamamoto** [comment]
クローズ
