### ISSUE TITLE
TOP：マップに別所弘明寺スクールを追加

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#52]
## ゴール
TOPのフッター付近に、教室紹介とまったく同じあしらいの別所弘明寺スクールのアクセスを追加

![image](https://user-images.githubusercontent.com/79657462/113018660-ba926400-91bb-11eb-96fb-75ca44eba6ae.png)

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら、TOPの日限丸山台スクールの下に同じ構成の別所弘明寺スクールを追加するのではなく、
あくまで教室紹介の別所弘明寺スクールのアクセスと同じものを追加するということであってますか？？
違和感がありますが。。

![image](https://user-images.githubusercontent.com/19180058/113028915-cb94a280-91c6-11eb-95f0-861841a87153.png)

![image](https://user-images.githubusercontent.com/19180058/113029002-e6ffad80-91c6-11eb-8191-f4597e173911.png)

**Comment by ryosuke-hamamoto** [comment]
TOPの丸山台スクールと同じ構成で、別所弘明寺スクールを追加。
です！
失礼しました！

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

深夜にありがとうございました。
Meetで話した通りの内容でプレビュー反映していると思いますので、ご確認お願い致します。

**Comment by takuan423** [comment]
失礼しました。そうだ、別所スクールの情報にまだなっていないでした。朝差し替えます。。！

**Comment by takuan423** [comment]
@ryosuke-hamamoto ちゃんと情報を別所弘明寺スクールのものに修正しました。ご確認お願い致しますmm

**Comment by ryosuke-hamamoto** [comment]
クローズ
