### ISSUE TITLE
問い合わせ：郵便番号の入力制限

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#53]
8文字入るので、7文字までしか入力できないように

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら現在の本番環境にて対応済みとなりますので、問題なければクローズお願いいたします。

**Comment by ryosuke-hamamoto** [comment]
ハイフンありにしてるから、8文字まで入る感じなんですね。

突っ込まれたら僕の方で改修するんで、クローズ
