### ISSUE TITLE
問い合わせ：SP入力時のズームアップ？

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#55]
スマホで入力する際、拡大されて
入力が終わっても拡大されたまま
伝わりづらいかもなんで、口頭で言いますわ！

忘れないためのissue

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら対応しました。

内容としては、フォントサイズ16px以下の場合はiphone側でズームしてしまうという機能になります。
そのため、フォントサイズに16pxをあてていて、以前よりも2px大きくなってしまっています。
ただ違和感を感じていないので、ご確認よろしくお願いいたします。

**Comment by ryosuke-hamamoto** [comment]
確認できないですー＞＜
ズームアップされてしまいますね。。。

**Comment by ryosuke-hamamoto** [comment]
やらないでいいです。
クローズ
