### ISSUE TITLE
ニュース：動画投稿のサムネ

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#56]
サムネは動画のキャプチャを自動で設定できるように
![image](https://user-images.githubusercontent.com/79657462/113417569-a12d2a00-93fe-11eb-859a-ff7d075fc022.png)

**Comment by ryosuke-hamamoto** [comment]
@k-kurihara 
解決したって理解でokですよね？
問題なければクローズしてください。

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら解決しておりますので、クローズします
