### ISSUE TITLE
企業情報：別所教室追加

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#57]
丸山台スクールのあとに、別所教室の情報を追加
![image](https://user-images.githubusercontent.com/79657462/113513134-0caffc80-95a3-11eb-8696-63d7484925a4.png)

**Comment by takuan423** [comment]
ローカルで対応済み

**Comment by takuan423** [comment]
@k-kurihara こちら対応しておりますので、WP反映お願いします。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応しましたので、ご確認お願い致します。

http://renewal.cosmojuku.com/company/

**Comment by ryosuke-hamamoto** [comment]
@takuan423 
共有漏れすいません
ミライコベツを削除でお願いします…！

本番を正にし、STG反映したらクローズください
https://cosmojuku.com/company/

**Comment by takuan423** [comment]
対応したのでクローズ
