### ISSUE TITLE
講師紹介：先生のテキストエリアを塾長たちと同じ大きさに

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#58]

**Comment by ryosuke-hamamoto** [comment]
![image](https://user-images.githubusercontent.com/79657462/113513185-484ac680-95a3-11eb-8fb9-eaa6bdd583b6.png)

**Comment by ryosuke-hamamoto** [comment]
![image](https://user-images.githubusercontent.com/79657462/119791199-916a2780-bf0f-11eb-89fb-9e500bfff84e.png)

治そうと思ったんだけど、よくわからず；

中村先生だけ、要素隠れちゃう

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちらも対応済みですのでご確認お願い致します。

http://renewal.cosmojuku.com/teachers/

**Comment by ryosuke-hamamoto** [comment]
クローズ
