### ISSUE TITLE
コスモジュクとは：通いやすい立地のテキスト変更

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#59]
日限山丸山台教室、別所弘明寺教室のどちらも、教室付近は夜間も明るく安全なのでお子さまおひとりの通塾も安心です。また、どちらの教室の前にも駐輪スペースを確保しており、塾の近辺は駐車可能な場所もございますので、自家用車での送迎もしやすい環境となっております。

![image](https://user-images.githubusercontent.com/79657462/113513204-6ca6a300-95a3-11eb-94ec-f14ddd4345b7.png)

**Comment by takuan423** [comment]
@k-kurihara こちら対応しておりますので、WP反映お願いします。

**Comment by ryosuke-hamamoto** [comment]
濵本の方で、本番反映済

勝手にやったけど大丈夫でしたでしょか？

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

ありがとうございます。問題ありません。マージしておきます。

**Comment by ryosuke-hamamoto** [comment]
STGの反映も確認OK
クローズ
