### ISSUE TITLE
全体：画像使用箇所でhoverアクションない箇所すべてに適用

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#6]
## ゴール
画像を使用している部分で、hoverのない箇所をすべてopacityで対応  

## 調整内容
- [ ] KVの特集バナー
- [x] コスモニュース記事
- [x] ヘッダーcosmoロゴ
- [x] フッターSNSリンク

**※コスモNEWSの下層で使ってるopacityと同じでいいです。※**

![2_opacity](https://user-images.githubusercontent.com/79657462/109482325-32884400-7ac1-11eb-89a0-4bd25a9abccc.png)

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応したので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
ＫＶ特集バナー確認願います

**Comment by takuan423** [comment]
@ryosuke-hamamoto こちら対応しましたので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
クローズ
