### ISSUE TITLE
コース紹介＆料金案内：大学受験コースの誤字修正

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#61]
「口座コマ数」→「講座コマ数」に変更

![image](https://user-images.githubusercontent.com/79657462/113555141-5c3f0880-9635-11eb-82d5-97607c507c2a.png)

**Comment by takuan423** [comment]
ローカルで対応ずみ

**Comment by takuan423** [comment]
@k-kurihara こちら対応しておりますので、WP反映お願いします。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 
こちら対応しましたので、ご確認お願い致します。

http://renewal.cosmojuku.com/course/

**Comment by ryosuke-hamamoto** [comment]
クローズ
