### ISSUE TITLE
お問い合わせ：LINEでカンタン問い合わせのタブ追加

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#63]
別所の「LINEでカンタンお問い合わせも！」を追加したい
タブ切り替えになるようにしたい
![img_03](https://user-images.githubusercontent.com/79657462/115027803-1c163a80-9eff-11eb-9d9b-fd502c2a78f6.png)

**Comment by takuan423** [comment]
@ryosuke-hamamoto 
こちら、「別所弘明寺」のLINEのURLとQRコードの支給をいただきたいですmm
JSとスタイル自体は実装済みです。

**Comment by ryosuke-hamamoto** [comment]
@takuan423 
QRはこちらに
https://drive.google.com/drive/u/1/folders/1ig-maOTwAEBR5Mq2cKWqDRxJ-_jcxdc5

別所弘明寺LINEのURLはこちら
https://lin.ee/sAu6xwG

**Comment by takuan423** [comment]
@ryosuke-hamamoto ありがとうございますmm

**Comment by takuan423** [comment]
@k-kurihara こちら対応しておりますので、WP反映お願いします。

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応しましたのでご確認お願い致します。

http://renewal.cosmojuku.com/contact/

**Comment by ryosuke-hamamoto** [comment]
@takuan423 
日限丸山台教室のQR、粗いな…。。

![image](https://user-images.githubusercontent.com/79657462/121343208-647d3200-c95d-11eb-92b5-f61161c6f391.png)


一番大きいサイズでもあれちゃうかな・・・？
差し替えてみて、粗さ軽減されてたらクローズしてください
![L (1)](https://user-images.githubusercontent.com/79657462/121343366-8d9dc280-c95d-11eb-98cd-159095567e4c.png)

**Comment by takuan423** [comment]
対応したのでクローズ
