### ISSUE TITLE
問い合わせ：戻るボタン押下時のデータ保持

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#65]
4月頭にSlackで質問した件です。

問合せの情報を戻るボタン押してもタブの情報が維持できるとよいのですが実装することは可能ですか？

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら試してみましたが、維持することは難しかったです。。。
無理やり維持する場合は、cookieで保存しておいて最後に開いたタブにすることはできますが、
サイトを離れてから、再度アクセスした場合もそのタブを開いてしまうことになってしまいます。
それでも良ければ時間はかかりますが、対応可能です。

**Comment by ryosuke-hamamoto** [comment]
了解です。
クローズしますー
