### ISSUE TITLE
TOP：リンク先の設定

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#7]
## ゴール
各種ページ内リンクを設定

## リンク先がまとめてる資料
https://docs.google.com/spreadsheets/d/1tgs3_grmcgztODBs_RSA6qlgXq-kbuXe/edit#gid=1355780221

### トップ
- [x] TOP > コスモジュクについて

- [x] TOP > コース詳細をみる

- [x] TOP > 記事一覧をみる

- [x] TOP > 公式Facebookはこちら

###  共通フッター

- [x] コース・料金
各エリアにアンカーリンク

- [x] 企業情報

- [x] お問い合わせ

- [x] Cosmo jukuロゴ

###  入塾の流れ＆よくあるご質問

- [x] よくあるご質問

(@k-kurihara @takuan423 )

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら対応いたしましたので、ご確認よろしくお願いいたします。

**Comment by ryosuke-hamamoto** [comment]
入塾の流れの「授業料はどれくらいですか？」はコース・料金に飛ばしてください。
![１](https://user-images.githubusercontent.com/79657462/110264126-e034af00-7ffb-11eb-8f7b-b468deb4fa51.png)

コスモジュクの活動「公式Facebookはこちら」は別タブで開くようにしてください

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら対応いたしましたので、ご確認よろしくお願いいたします。

**Comment by ryosuke-hamamoto** [comment]
クローズ
