### ISSUE TITLE
TOP：KVエリアの表示調整

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#8]
## ゴール
PCSP時、KVの要素がどんな端末でもすべて表示されるように調整

## 調整内容
キャプチャの要素がMac/Windows関わらず要素がワンビューで表示

PC：
![6_kv](https://user-images.githubusercontent.com/79657462/109484639-05896080-7ac4-11eb-8f1d-5de4d487a606.png)

SP：
![7_spkv](https://user-images.githubusercontent.com/79657462/109491813-679a9380-7acd-11eb-908a-88c5ebe7b622.png)

(@k-kurihara @takuan423 )

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら対応いたしましたので、ご確認よろしくお願いいたします。
自分のmacPCで表示ができるような状態としています。
自分の意見だと、リード文まで今回ファーストビューに入れていますが、
リード文はファーストビューに入れないほうがきれいかなと思いました。

<img width="1439" alt="スクリーンショット 2021-03-08 9 36 31" src="https://user-images.githubusercontent.com/12445131/110261019-d7d77680-7ff1-11eb-9aec-e69d4065fc07.png">

**Comment by ryosuke-hamamoto** [comment]
@k-kurihara 
確かに視認性なども併せると、動画の下に持ってきた方がいいですね。
ただ、ＦＶの下に持ってくると、ブリッジの言葉としては弱いんでＦＶ内には入れたいんですよね。。
たとえば添付のイメージがＦＶになるような感じとかどうですか？？動画小さくなりすぎちゃいますかね。

ちなみに僕のパソコンが1920 x 1080でWindowsで比較的多い画角になるんですが、見切れちゃってます！

![image](https://user-images.githubusercontent.com/79657462/110262769-0f492180-7ff8-11eb-9e7c-526a47a57c1f.png)

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
動画のサイズ調整して見ましたので、確認お願いします！
また、windowsの画角でのスクショもらえると助かります！
macだとこんな感じです！
<img width="1440" alt="スクリーンショット 2021-03-08 10 40 34" src="https://user-images.githubusercontent.com/12445131/110263694-ccd51400-7ffa-11eb-80e9-a809ced241e0.png">

**Comment by ryosuke-hamamoto** [comment]
添付のような惜しい感じに！！
![image](https://user-images.githubusercontent.com/79657462/110263828-2d645100-7ffb-11eb-91e2-bd0fb62040c2.png)

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
調整してみましたので、ご確認よろしくお願いいたします！

**Comment by ryosuke-hamamoto** [comment]
こんなこんな感じです。
![image](https://user-images.githubusercontent.com/79657462/110354236-4ca2c300-807b-11eb-8aa8-038e13660bc8.png)

スマホの方も同じく調整進めてほしいですｍｍ

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
PCもうちょっと。。。
スマホの方って、どうしたら良いんでしたっけ・・・！？
コピーまでFVで見せたい感じですか？？

**Comment by ryosuke-hamamoto** [comment]
コピーは見せないでＯＫです。

iPhone8の画角で、表題の見た目になればＯＫっすね。
https://github.com/k-kurihara/cosmo-renewal/issues/8#issue-818772723


現状
![iOS の画像 (15)](https://user-images.githubusercontent.com/79657462/110355610-c5eee580-807c-11eb-8742-d36eb3746531.png)

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
こちら対応いたしましたので、ご確認よろしくお願いいたします。

ちなみにmacPCでの見た目がこちらです
<img width="1436" alt="スクリーンショット 2021-03-09 20 09 22" src="https://user-images.githubusercontent.com/12445131/110462981-b622e000-8114-11eb-9905-b152c84d2fa8.png">

自分の実機iphone12ではこの見た目とほぼ同じです。
（タスクバーが下に表示されるので、リード文が今日の「出来た」〜の行のみが見えている状態です）
<img width="380" alt="スクリーンショット 2021-03-09 20 10 00" src="https://user-images.githubusercontent.com/12445131/110463041-c3d86580-8114-11eb-89f5-134a7accdb89.png">

**Comment by ryosuke-hamamoto** [comment]
@k-kurihara 
iPhone8の下のバー問題あるなーーーーー
![iOS の画像 (16)](https://user-images.githubusercontent.com/79657462/110471350-63025a80-811f-11eb-91ad-b025091ffb74.png)

**Comment by k-kurihara** [comment]
@ryosuke-hamamoto 
文字だけ上に上げてみました！

**Comment by ryosuke-hamamoto** [comment]
おけっす。これで
クローズします。

（文字の視認性だけ、プレビュー展開後言われるかもってくらい）
