### ISSUE TITLE
TOP：チャットボットのhover演出

### ISSUE THREAD

**Issue by ryosuke-hamamoto** [k-kurihara/cosmo-renewal#9]
## ゴール
トップページの右下に追従してくるチャットボットボタンをhover時の動きを追加

## 調整内容
色が反転し、アイコンが少し上に上がる
![5_chatbot](https://user-images.githubusercontent.com/79657462/109484916-5c8f3580-7ac4-11eb-8ba9-797e2a8e090f.png)

(@k-kurihara @takuan423 )

**Comment by takuan423** [comment]
@ryosuke-hamamoto 

こちら対応したので、ご確認お願い致します。

**Comment by ryosuke-hamamoto** [comment]
ＯＫ
クローズ
